---
- name: Create promtail config volume
  community.docker.docker_volume:
    name: promtail_config

- name: Ensure grafana/promtail image is pulled
  community.docker.docker_image:
    name: docker.io/grafana/promtail
    source: pull
    force_source: yes
  register: pulled

- name: Remove promtail container
  community.docker.docker_container:
    name: promtail
    state: absent
  when: pulled.changed

- name: Get infos on promtail container
  community.docker.docker_container_info:
    name: promtail
  register: result

- name: Create promtail container
  community.docker.docker_container:
    command: ["-config.file=/mnt/config/promtail-config.yaml", "-config.expand-env=true"]
    env:
     HOST: "{{ ansible_nodename }}"
    image: docker.io/grafana/promtail
    mounts:
     - source: promtail_config
       target: /mnt/config
     - read_only: yes
       source: /var/log/
       target: /var/log
       type: bind
     - read_only: yes
       source: /var/lib/docker/containers/
       target: /var/lib/docker/containers
       type: bind
    name: promtail
    networks:
     - name: app-network
    restart_policy: unless-stopped
    state: started
  when:
    pulled.changed
    or
    result.exists == false

- name: Create tmp promtail directory
  ansible.builtin.file:
    path: /opt/tmp-promtail
    state: directory
  when:
    result.exists == false

- name: Copy promtail file
  ansible.builtin.template:
    src: promtail-config.yaml.j2
    dest: /opt/tmp-promtail/promtail-config.yaml
  when:
    result.exists == false

- name: Copy config file into promtail container
  shell: docker cp /opt/tmp-promtail/promtail-config.yaml promtail:/mnt/config
  when:
    result.exists == false

- name: Remove tmp promtail directory
  ansible.builtin.file:
    path: /opt/tmp-promtail
    state: absent
  when:
    result.exists == false

- name: Restart promtail container
  community.docker.docker_container:
    name: promtail
    restart: yes
  when:
    result.exists == false

- name: Ensure beevelop/nginx-basic-auth image is pulled
  community.docker.docker_image:
    name: docker.io/beevelop/nginx-basic-auth
    source: pull
    force_source: yes
  register: pulled_nginx

- name: Remove nginx container
  community.docker.docker_container:
    name: promtail-nginx
    state: absent
  when: pulled_nginx.changed

- name: Get infos on nginx container
  community.docker.docker_container_info:
    name: promtail-nginx
  register: result_nginx

- name: Create nginx container
  community.docker.docker_container:
    image: docker.io/beevelop/nginx-basic-auth
    name: promtail-nginx
    networks:
     - name: app-network
    env:
      FORWARD_HOST: "promtail"
      FORWARD_PORT: "9080"
      HTPASSWD: "{{ system_promtail_nginx_htpasswd }}"
    restart_policy: unless-stopped
    state: started
  when:
    pulled_nginx.changed
    or
    result_nginx.exists == false
