---
- name: Create promtail config volume
  community.docker.docker_volume:
    name: "{{ system_promtail_docker_volume }}"

- name: Ensure promtail image is pulled
  community.docker.docker_image:
    name: "{{ system_promtail_docker_image }}"
    source: pull
    force_source: yes
  register: pulled

- name: Remove promtail container
  community.docker.docker_container:
    name: "{{ system_promtail_docker_container }}"
    state: absent
  when: pulled.changed

- name: Get infos on promtail container
  community.docker.docker_container_info:
    name: "{{ system_promtail_docker_container }}"
  register: result

- name: Create promtail container
  community.docker.docker_container:
    command: ["-config.file=/mnt/config/promtail-config.yaml", "-config.expand-env=true"]
    env:
     HOST: "{{ ansible_nodename }}"
    image: "{{ system_promtail_docker_image }}"
    mounts:
     - source: "{{ system_promtail_docker_volume }}"
       target: /mnt/config
     - read_only: yes
       source: /var/log/
       target: /var/log
       type: bind
     - read_only: yes
       source: /var/lib/docker/containers/
       target: /var/lib/docker/containers
       type: bind
    name: "{{ system_promtail_docker_container }}"
    networks:
     - name: "{{ system_promtail_docker_network }}"
    restart_policy: unless-stopped
    state: started
  when:
    pulled.changed
    or
    result.exists == false

- name: Create tmp promtail directory
  ansible.builtin.file:
    path: "{{ system_promtail_tmp_dir }}"
    state: directory
  when:
    result.exists == false

- name: Copy promtail file
  ansible.builtin.template:
    src: promtail-config.yaml.j2
    dest: "{{ system_promtail_tmp_dir }}/promtail-config.yaml"
  when:
    result.exists == false

- name: Copy config file into promtail container
  shell: "docker cp {{ system_promtail_tmp_dir }}/promtail-config.yaml promtail:/mnt/config"
  when:
    result.exists == false

- name: Remove tmp promtail directory
  ansible.builtin.file:
    path: "{{ system_promtail_tmp_dir }}"
    state: absent
  when:
    result.exists == false

- name: Restart promtail container
  community.docker.docker_container:
    name: "{{ system_promtail_docker_container }}"
    restart: yes
  when:
    result.exists == false

- name: Ensure beevelop/nginx-basic-auth image is pulled
  community.docker.docker_image:
    name: "{{ system_promtail_nginx_docker_image }}"
    source: pull
    force_source: yes
  register: pulled_nginx

- name: Remove nginx container
  community.docker.docker_container:
    name: "{{ system_promtail_docker_container }}-nginx"
    state: absent
  when: pulled_nginx.changed

- name: Get infos on nginx container
  community.docker.docker_container_info:
    name: "{{ system_promtail_docker_container }}-nginx"
  register: result_nginx

- name: Create nginx container
  community.docker.docker_container:
    image: docker.io/beevelop/nginx-basic-auth
    name: "{{ system_promtail_docker_container }}-nginx"
    networks:
     - name: "{{ system_promtail_docker_network }}"
    env:
      FORWARD_HOST: "{{ system_promtail_docker_container }}"
      FORWARD_PORT: "9080"
      HTPASSWD: "{{ system_promtail_nginx_htpasswd }}"
    restart_policy: unless-stopped
    state: started
  when:
    pulled_nginx.changed
    or
    result_nginx.exists == false
